name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.1"
          - "7.4"
          - "8.1"

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Conventionally you would hash "composer.lock", but we don't commit
          # that, so we hash on "composer.json" instead.
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

      # We have to downgrade the php-cs-fixer dependency as the one we use to
      # format does not support all of our PHP versions.
      - name: Downgrade php-cs-fixer
        run: composer require --dev "friendsofphp/php-cs-fixer:3.5.0" --ignore-platform-reqs

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run phpstan
        run: make phpstan

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - AUTOLOAD=0
          - AUTOLOAD=1
        php-version:
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}

      # We have to downgrade the php-cs-fixer dependency as the one we use to
      # format does not support all of our PHP versions.
      - name: Downgrade php-cs-fixer
        run: composer require --dev "friendsofphp/php-cs-fixer:3.5.0" --ignore-platform-reqs

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Start stripe-mock
        run: docker pull stripe/stripe-mock && docker run -d -p 12111-12112:12111-12112 stripe/stripe-mock && sleep 5

      - name: Run test suite
        run: |
          php --version
          ./build.php $env:AUTOLOAD
